# Generated by Django 3.2.6 on 2021-08-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usertable',
            table='test_user',
        ),
    ]
