# Generated by Django 3.2.6 on 2021-08-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_alter_usertable_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='age',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
